# Copyright (c) Meta Platforms, Inc. and affiliates.

name: API Reference Examples CI - Go
on:
  push:
    branches:
    - main
    paths:
    - 'api-reference-examples/go/**'
    - '.github/workflows/golang-ci.yaml'
  pull_request:
    branches:
    - main
    paths:
    - 'api-reference-examples/go/**'
    - '.github/workflows/golang-ci.yaml'

defaults:
  run:
    working-directory: api-reference-examples/go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '^1.15.0'
    - name: Install testify
      run: |
        go env -w GO111MODULE=auto
        go get github.com/stretchr/testify
    - name: Run tests
      run: |
        go test ./...
