# Copyright (c) Meta Platforms, Inc. and affiliates.

name: python-threatexchange CI
on:
  push:
    branches:
      - main
    paths:
      - "python-threatexchange/**"
      - ".github/workflows/python-threatexchange-ci.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "python-threatexchange/**"
      - ".github/workflows/python-threatexchange-ci.yaml"

defaults:
  run:
    working-directory: python-threatexchange

jobs:
  lint-and-types:
    name: Lint and Type-Check python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install vpdq dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev pkg-config cmake ffmpeg libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
      - name: Check code format
        run: |
          black --check . --diff
      - name: Check python types
        run: |
          python -m mypy threatexchange
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ffmpeg
        id: ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
      - name: Install vpdq dependencies
        run: |
          sudo apt-get install -y python3-dev pkg-config cmake ffmpeg libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install -e .[dev,extensions]
      - name: Test with pytest
        run: |
          py.test
